export const Medicins = [
    {
        id: 1,
        item: "Paracetamol",
        price: 1500,
        dosage:'1-M/A/E',
        instruction:'After Meal',
        quantity:1,
        amount:1000,
    },
    {
        id: 2,
        item: "Paracetamol",
        price: 1500,
        dosage:'1-M/A/E',
        instruction:'After Meal',
        quantity:1,
        amount:1000,
    },
    {
        id: 3,
        item: "Paracetamol",
        price: 1500,
        dosage:'1-M/A/E',
        instruction:'After Meal',
        quantity:1,
        amount:1000,
    },
    // {
    //     id: 4,
    //     item: "Paracetamol",
    //     price: 1500,
    //     dosage:'1-M/A/E',
    //     instruction:'After Meal',
    //     quantity:1,
    //     amount:1000,
    // },
    // {
    //     id: 5,
    //     item: "Paracetamol",
    //     price: 1500,
    //     dosage:'1-M/A/E',
    //     instruction:'After Meal',
    //     quantity:1,
    //     amount:1000,
    // },
]